apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 022698001278.dkr.ecr.us-west-2.amazonaws.com/aknys-demo-frontend
  newName: 022698001278.dkr.ecr.us-west-2.amazonaws.com/aknys-demo-frontend
  newTag: 366fdabd
- name: 022698001278.dkr.ecr.us-west-2.amazonaws.com/demo-frontend
  newName: 022698001278.dkr.ecr.us-west-2.amazonaws.com/demo-frontend
  newTag: abcdefg
resources:
- ../../base
patches:
- path: front-deployment-patch.yaml
- path: front-service-patch.yaml
- path: ingress-patch.yaml
# - path: flask-deployment-patch.yaml
- path: nodejs-deployment-patch.yaml
